spring:
  datasource:
    url: jdbc:mysql://119.29.79.248:3306/spring?serverTimezone=GMT%2B8&useSSL=false&false
    username: root
    password: cc135792468.
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.spring.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl